### ISSUE TITLE
소스코드를 수정 및 재배포해도 될까요??

### ISSUE THREAD

**Issue by pjy0121** [ZeroPage/NetworkOmokProject#1]
안녕하세요. 한국분이시니 국어로 남깁니다...
저는 대학생입니다. 지금 수업에서 프로젝트를  하나 하고 있는데 제 채팅프로그램에 삽입할 오픈소스로 된 오목 프로그램이 필요한데 이 페이지에 라이선스가 없더라구요.. 
원래 github에서 라이선스를 표시하지 않은 소스코드는 읽거나 사용할 수는 있지만 변경은 불가능하다고 해서요. 허용해주신다면 제 프로젝트에서 이 소스코드를 쓰고 싶습니다.

**Comment by inclue** [comment]
라이센스를 올려두었으니 맞게 사용하시면 됩니다.

**Comment by pjy0121** [comment]
감사합니다~

**Comment by pjy0121** [comment]
감사합니다!! 잘쓰겠습니다.

2017-05-31 14:55 GMT+09:00 박인서 <notifications@github.com>:
